# Generated by Django 3.1.5 on 2022-02-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('growth', models.IntegerField(blank=True, null=True, verbose_name='Рост')),
                ('bust', models.IntegerField(blank=True, null=True, verbose_name='Обхват груди')),
                ('jacket', models.IntegerField(blank=True, choices=[(1, '39/1'), (2, '39/2')], null=True, verbose_name='Куртка')),
                ('shoes', models.IntegerField(blank=True, choices=[(1, '37'), (2, '38')], null=True, verbose_name='Обувь')),
                ('cap', models.IntegerField(blank=True, null=True, verbose_name='Фуражка')),
                ('collar', models.IntegerField(blank=True, choices=[(1, '39/1'), (2, '39/2')], null=True, verbose_name='Воротничок')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Арматурная карточка',
                'verbose_name_plural': 'Арматурные карточки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('clothes_title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('wear_time', models.IntegerField(verbose_name='Сроки носки, мес.')),
                ('nomenclature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номенклатура')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Наименование предмета',
                'verbose_name_plural': 'Наименования предметов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClothesInNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_count', models.IntegerField(verbose_name='Количество по норме')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothes', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Наименование в норме',
                'verbose_name_plural': 'Наименования в норме',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('rank', models.CharField(max_length=50, verbose_name='Звание')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('subdivision_short_name', models.CharField(max_length=255, verbose_name='Короткое название подразделения (только заглавные английские буквы)')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('subdivision_name',),
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('norm_title', models.CharField(max_length=255, verbose_name='Название нормы')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
                ('clothes_list', models.ManyToManyField(blank=True, through='clothing.ClothesInNorm', to='clothing.Clothes', verbose_name='Наименования')),
            ],
            options={
                'verbose_name': 'Норма',
                'verbose_name_plural': 'Нормы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], null=True, verbose_name='Пол')),
                ('kind', models.IntegerField(choices=[(1, 'Курсант'), (2, 'Офицер'), (3, 'Гражданский')], verbose_name='Тип сотрудника')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.position', verbose_name='Должность')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing.rank', verbose_name='Звание')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='clothesinnorm',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.norm', verbose_name='Норма'),
        ),
        migrations.CreateModel(
            name='ClothesInCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.card', verbose_name='Арматурная карточка')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothes', verbose_name='Вещь')),
            ],
            options={
                'verbose_name': 'Вещь в карточке',
                'verbose_name_plural': 'Вещи в карточке',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='clothes',
            field=models.ManyToManyField(blank=True, through='clothing.ClothesInCard', to='clothing.Clothes', verbose_name='Имущество'),
        ),
        migrations.AddField(
            model_name='card',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.employee', verbose_name='Сотрудник/курсант'),
        ),
        migrations.AddField(
            model_name='card',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.norm', verbose_name='Норма'),
        ),
    ]
