# Generated by Django 4.0.2 on 2022-03-17 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_dimension', models.CharField(max_length=20, verbose_name='Размер фуражки')),
            ],
            options={
                'verbose_name': 'Размер (фуражки)',
                'verbose_name_plural': 'Размеры (фуражки)',
                'ordering': ('cap_dimension',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('card_number', models.CharField(max_length=100, verbose_name='Номер карты')),
                ('growth', models.IntegerField(blank=True, null=True, verbose_name='Рост')),
                ('bust', models.IntegerField(blank=True, null=True, verbose_name='Обхват груди')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
                ('cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.capdimensions', verbose_name='Фуражка')),
            ],
            options={
                'verbose_name': 'Арматурная карточка',
                'verbose_name_plural': 'Арматурные карточки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('clothes_title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('nomenclature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номенклатура')),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена')),
                ('has_to_be_deposited', models.BooleanField(default=False, verbose_name='Подлежит сдаче')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Наименование предмета',
                'verbose_name_plural': 'Наименования предметов',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('course_name',),
            },
        ),
        migrations.CreateModel(
            name='DescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothes', verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=20, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер (куртки)',
                'verbose_name_plural': 'Размеры (куртки)',
                'ordering': ('dimension',),
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('norm_title', models.CharField(max_length=255, verbose_name='Название нормы')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Норма',
                'verbose_name_plural': 'Нормы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_clothes', models.ManyToManyField(blank=True, to='clothing.Clothes', verbose_name='Совокупность вещей')),
            ],
            options={
                'verbose_name': 'Позиция для нормы',
                'verbose_name_plural': 'Позиции для нормы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('rank', models.CharField(max_length=50, verbose_name='Звание')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ShoesDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_dimension', models.CharField(max_length=20, verbose_name='Размер обуви')),
            ],
            options={
                'verbose_name': 'Размер (обуви)',
                'verbose_name_plural': 'Размеры (обуви)',
                'ordering': ('shoes_dimension',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('subdivision_short_name', models.CharField(max_length=255, verbose_name='Короткое название подразделения (только заглавные английские буквы)')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('subdivision_name',),
            },
        ),
        migrations.CreateModel(
            name='NormItemsInNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_count', models.IntegerField(verbose_name='Количество по норме')),
                ('wear_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сроки носки, мес.')),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.norm', verbose_name='Норма')),
                ('norm_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.normitem', verbose_name='Наименования')),
            ],
            options={
                'verbose_name': 'Наименование в норме',
                'verbose_name_plural': 'Наименования в норме',
                'ordering': ('norm__norm_title',),
            },
        ),
        migrations.AddField(
            model_name='norm',
            name='items_list',
            field=models.ManyToManyField(blank=True, through='clothing.NormItemsInNorm', to='clothing.NormItem', verbose_name='Наименования'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи/сдачи')),
                ('movement_direction', models.IntegerField(choices=[(1, 'Выдача'), (2, 'Сдача')], default=1, verbose_name='Движение (выдача / сдача)')),
                ('has_replacement', models.BooleanField(default=False, verbose_name='Имеет замену')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Получено по сертификату')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер аттестата')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.card', verbose_name='Арматурная карточка')),
                ('movement_description', models.ManyToManyField(blank=True, through='clothing.DescriptionItem', to='clothing.Clothes', verbose_name='Описание движения наименований')),
                ('norm_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.normitem', verbose_name='Позиция в норме')),
            ],
            options={
                'verbose_name': 'Движение в карточке',
                'verbose_name_plural': 'Движения в карточке',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Группа')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('group_name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], default=1, null=True, verbose_name='Пол')),
                ('kind', models.IntegerField(choices=[(1, 'Курсант'), (2, 'Офицер'), (3, 'Гражданский')], verbose_name='Тип сотрудника')),
                ('is_on_decree', models.BooleanField(default=False, verbose_name='В декрете')),
                ('decree_start', models.DateField(blank=True, null=True, verbose_name='Начало декрета')),
                ('decree_finish', models.DateField(blank=True, null=True, verbose_name='Окончание декрета')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('enlisted', models.DateField(blank=True, null=True, verbose_name='Зачислен')),
                ('excluded', models.DateField(blank=True, null=True, verbose_name='Исключен')),
                ('personal_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Персональный номер')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.group', verbose_name='Группа')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.position', verbose_name='Должность')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing.rank', verbose_name='Звание')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='descriptionitem',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.movement', verbose_name='Движение в карточке'),
        ),
        migrations.AddField(
            model_name='card',
            name='collar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collar', to='clothing.dimensions', verbose_name='Воротничок'),
        ),
        migrations.AddField(
            model_name='card',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.employee', verbose_name='Сотрудник/курсант'),
        ),
        migrations.AddField(
            model_name='card',
            name='jacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.dimensions', verbose_name='Куртка'),
        ),
        migrations.AddField(
            model_name='card',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.norm', verbose_name='Норма'),
        ),
        migrations.AddField(
            model_name='card',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothing.shoesdimensions', verbose_name='Обувь'),
        ),
    ]
