# Generated by Django 3.1.5 on 2022-02-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_date1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_date2',
        ),
    ]
