# Generated by Django 3.1.5 on 2022-02-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_auto_20220208_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='collar',
            field=models.IntegerField(blank=True, choices=[(1, '39/1'), (2, '39/2')], null=True, verbose_name='Воротничок'),
        ),
        migrations.AlterField(
            model_name='card',
            name='jacket',
            field=models.IntegerField(blank=True, choices=[(1, '39/1'), (2, '39/2')], null=True, verbose_name='Куртка'),
        ),
        migrations.CreateModel(
            name='ClothesInCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.card', verbose_name='Арматурная карточка')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothes', verbose_name='Вещь')),
            ],
            options={
                'verbose_name': 'Вещь в карточке',
                'verbose_name_plural': 'Вещи в карточке',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='clothes',
            field=models.ManyToManyField(through='clothing.ClothesInCard', to='clothing.Clothes', verbose_name='Имущество'),
        ),
    ]
