# Generated by Django 4.0.2 on 2022-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_clothesincard_has_replacement_alter_capdimensions_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesincard',
            name='movement',
            field=models.IntegerField(choices=[(1, 'Выдача'), (2, 'Сдача')], default=1, verbose_name='Движение (выдача / сдача)'),
        ),
    ]
