# Generated by Django 2.2.7 on 2022-03-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_auto_20220325_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='certificate_wear_time',
            field=models.IntegerField(default=12, verbose_name='Срок носки по сертификату (мес.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='replacing_what',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing.Movement', verbose_name='Замена позиции из аттестата'),
        ),
    ]
