# Generated by Django 3.1.5 on 2022-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_auto_20220208_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-id',), 'verbose_name': 'Арматурная карточка', 'verbose_name_plural': 'Арматурные карточки'},
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
