# Generated by Django 2.2.7 on 2022-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_auto_20220329_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='certificate_wear_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок носки по сертификату (мес.)'),
        ),
    ]
