# Generated by Django 4.0.2 on 2022-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_clothesincard_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер карты'),
            preserve_default=False,
        ),
    ]
