# Generated by Django 3.1.5 on 2022-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_auto_20220209_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='clothesincard',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='clothesincard',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='norm',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='norm',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='position',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='rank',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
