# Generated by Django 3.1.5 on 2022-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_auto_20220209_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='clothes',
            field=models.ManyToManyField(blank=True, through='clothing.ClothesInCard', to='clothing.Clothes', verbose_name='Имущество'),
        ),
    ]
