# Generated by Django 2.2.7 on 2022-03-31 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_auto_20220331_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decree_start', models.DateField(verbose_name='Начало декрета')),
                ('decree_finish', models.DateField(blank=True, null=True, verbose_name='Окончание декрета')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
