# Generated by Django 4.0.2 on 2022-03-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_course_group_employee_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothesinnorm',
            options={'ordering': ('clothes__clothes_title',), 'verbose_name': 'Наименование в норме', 'verbose_name_plural': 'Наименования в норме'},
        ),
        migrations.AddField(
            model_name='clothesincard',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер аттестата'),
        ),
        migrations.AddField(
            model_name='clothesincard',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='clothesincard',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='Получено по сертификату'),
        ),
    ]
