# Generated by Django 4.0.2 on 2022-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_alter_clothesinnorm_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ('-id',), 'verbose_name': 'Наименование предмета', 'verbose_name_plural': 'Наименования предметов'},
        ),
        migrations.AddField(
            model_name='employee',
            name='enlisted',
            field=models.DateField(blank=True, null=True, verbose_name='Зачислен'),
        ),
        migrations.AddField(
            model_name='employee',
            name='excluded',
            field=models.DateField(blank=True, null=True, verbose_name='Исключен'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Персональный номер'),
        ),
    ]
