# Generated by Django 4.0.2 on 2022-03-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0011_clothes_interchange_alter_capdimensions_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='interchange',
        ),
    ]
