# Generated by Django 4.0.2 on 2022-03-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_clothesinnorm_interchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='interchange',
        ),
    ]
