# Generated by Django 4.0.2 on 2022-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0015_remove_clothes_interchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesinnorm',
            name='interchange',
            field=models.ManyToManyField(blank=True, null=True, related_name='interchange_cl', to='clothing.Clothes', verbose_name='Считается совместно с ...'),
        ),
    ]
